# Generated by Django 4.0.1 on 2022-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_registration_delete_useregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
