# Generated by Django 4.0.1 on 2022-01-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_alter_registration_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
