# Generated by Django 4.0.1 on 2022-01-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0004_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
