# Generated by Django 4.0.1 on 2022-01-13 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0005_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 4, 53, 23, 469334, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
